# Generated by Django 5.1.2 on 2024-10-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at', 'read')},
        ),
    ]
