# Generated by Django 5.1.2 on 2024-10-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('read', '-created_at')},
        ),
    ]
