# Generated by Django 5.1.2 on 2024-10-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_favorite_notification_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tag',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
