# Generated by Django 5.1.2 on 2024-10-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_article_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
