# Generated by Django 5.1.2 on 2024-10-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_article_options_article_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
