# Generated by Django 5.1.2 on 2024-10-26 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_customuser_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
